In [1]:
import pandas as pd

In [23]:
class Patient:
    def __init__(self, first_name, last_name, birthday, height_cm, weight, bmi):
        self.first_name = first_name
        self.last_name = last_name
        self.birthday = birthday
        self.height_cm = height_cm
        self.weight = weight
        self.bmi = bmi 

    def __repr__(self):
        return f"Patient(vorname={self.first_name!r},nachname={self.last_name!r},))"
    
    def height_m(self):
        return self.height_cm / 100

    def is_tall(self):
        return self.height_cm >= 180
    
    def ist_normalgewicht(self):
        return (18<=self.bmi) and (self.bmi<=25)

In [ ]:
df = pd.read_pickle("patient.pk")
df["Patient_Obj"] = df.apply(
    lambda row:
    Patient(
    row["Vorname"], 
    row["Nachname"], 
    row["Geburtsdatum"], 
    row["Größe_cm"],
    row["Gewicht_kg"],
    row["BMI"],
    ),
    axis = 1 # zeilenweise entlang der Spalte
)

# Aufgabe: 
# 1. Erstellen Sie eine Spalte mit Größe in m
# 2. Listen Sie alle großen Patienten
# 3. Erstellen Sie eine Übersicht 
# für Durchschnittskörpergröße in m nach Geschlecht
# 4. Erweitern Sie die Klasse um Attribute Gewicht und BMI
# Erstellen Sie eine Klassenmethode ist_normalgewicht(18<=bmi<=25). 
# Wer sind die 12 jüngsten Patienten mit Normalgewicht.

In [ ]:
df["Größe_m"] = df["Patient_Obj"].apply(lambda p: p.height_m()) # 1.
df[df["Patient_Obj"].apply(lambda p: p.is_tall())] # Listen von großen Patienten
df.groupby("Geschlecht")[["Größe_m"]].mean()

             Größe_m
Geschlecht
divers      1.798545
männlich    1.798016
weiblich    1.800779

In [33]:
df[df["Patient_Obj"].apply(lambda p: p.ist_normalgewicht())].sort_values("Alter").head(12)[["Alter","Nachname"]]

       Alter      Nachname
5685       1  Klingelhöfer
1232       1         Meyer
28788      1        Wesack
28461      1      Hartmann
12169      1          Huhn
28355      1      Fliegner
7773       1      Gotthard
27771      1       Haering
49346      1        Ladeck
39046      1      Gröttner
1496       1         Mende
27158      1        Scholz

In [38]:
df["Geschlecht"] = df["Geschlecht"].astype("category")
df.info()
df["Geschlecht"]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   PatientenID         50000 non-null  object
 1   Versichertennummer  50000 non-null  object
 2   Vorname             50000 non-null  object
 3   Nachname            50000 non-null  object
 4   Geburtsdatum        50000 non-null  object
 5   Geschlecht          50000 non-null  category
 6   Adresse             50000 non-null  object
 7   Telefon             50000 non-null  object
 8   Email               50000 non-null  object
 9   Blutgruppe          50000 non-null  object
 10  Letzer_Besuch       50000 non-null  object
 11  Hausarzt            50000 non-null  object
 12  Größe_cm            50000 non-null  int64
 13  Gewicht_kg          50000 non-null  int64
 14  Raucher             50000 non-null  bool
 15  Allergien           50000 non-null  object
 16  Letzes_EKG          50000 non-null  object
 17  BMI                 50000 non-null  float64
 18  Familienstand       50000 non-null  object
 19  Beruf               50000 non-null  object
 20  Alter               50000 non-null  int32
 21  Altersgruppe        50000 non-null  object
 22  Patient_Obj         50000 non-null  object
 23  Größe_m             50000 non-null  float64
dtypes: bool(1), category(1), float64(2), int32(1), int64(2), object(17)
memory usage: 8.3+ MB

0        weiblich
1          divers
2        weiblich
3        weiblich
4          divers
           ...
49995      divers
49996    männlich
49997    weiblich
49998    weiblich
49999    männlich
Name: Geschlecht, Length: 50000, dtype: category
Categories (3, object): ['divers', 'männlich', 'weiblich']